format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_usbhs_index}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_USBHS_MULTI_DEVICE_SUPPORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbhs_index, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_USBHS_MULTI_HOST_SUPPORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbhs_index, value: 'false'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_usbhs_index}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_USB_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usbhs_index_0, value: PERIPHERAL_USB_0}
      - type: Boolean
        attributes: {id: ENABLE_DRV_USB_DEVICE_SOURCE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usbhs_index_0, value: 'true'}
      - type: Boolean
        attributes: {id: ENABLE_DRV_USB_HOST_SOURCE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usbhs_index_0, value: 'false'}
      - type: Combo
        attributes: {id: USB_OPERATION_MODE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usbhs_index_0, value: Device}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: usb_peripheral_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: peripheral_usb_0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USBHS0}
- type: ElementPosition
  attributes: {x: '237', y: '615', id: drv_usbhs_index}
