package:
  format-version: "1.0.0"
  name: "gfx_apps_pic32cz_ca"
  version: "v3.0.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "gfx"
      type: "package"
      version: "v3.14.0"
    - name: "usb"
      type: "package"
      version: "v3.11.0"
    - name: "bsp"
      type: "package"
      version: "v3.18.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.18.1"
    - name: "csp"
      type: "package"
      version: "v3.18.2"
    - name: "core"
      type: "package"
      version: "v3.13.2"
